Добавлен учёт параметров ИБ при работе с пользователями хранилища
vanessa-opensource/vanessa-runner pull request #435
Opened 2021-05-13 13:39 UTC by MikhailSolntsev

При работе с пользователями хранилища теперь учитываются переданные параметры информационной базы.
Критично для случаев, когда нет лицензии на файловые базы

2021-06-01 10:18 UTC, artbear requested changes
Полезная доработка.

есть небольшое предложение.

2021-06-01 10:18 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +	КонецЕсли;
Добавленный код дублируется в 3х местах. 

Предлагаю выделить общий метод и использовать его.

2021-08-21 07:00 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +	КонецЕсли;
@MikhailSolntsev будешь исправлять?

2021-08-31 08:52 UTC, MikhailSolntsev commented on src/Классы/МенеджерКонфигуратора.os
> +	КонецЕсли;
Буду, чуть позже, пока не до него

2022-03-05 16:11 UTC, artbear approved these changes

2022-03-05 16:11 UTC, merged

2022-03-05 16:12 UTC, artbear commented
@MikhailSolntsev Большое спасибо!