УДаление Добавление ИБ в кластер
vanessa-opensource/vanessa-runner pull request #437
Opened 2021-05-27 02:32 UTC by Barrya42

Добавлено 2 команды:
Для создания ИБ
Для удаления ИБ

2021-06-01 10:16 UTC, artbear requested changes
Полезная доработка по созданию\удаления ИБ в кластере, до которой у нас никак не доходили руки.
Большущее спасибо!

но есть вопросы по реализации.
посмотри мои замечания.

2021-06-01 10:16 UTC, artbear commented on src/Классы/КомандаСоздатьИнформационнуюБазу.os
> +	КонецЕсли;
Ошибка в условии 
```
Если НЕ ЗначениеЗаполнено(мНастройки.ИдентификаторКластера) Тогда
		КомандаВыполнения = КомандаВыполнения + "--cluster=""" + ИдентификаторКластера + """ ";
КонецЕсли;
```
ведь в этом случае, если кластер задан, он не будет установлен

2021-06-01 10:16 UTC, artbear commented on src/Классы/КомандаСоздатьИнформационнуюБазу.os
> +		КомандаВыполнения = КомандаВыполнения + "--cluster=""" + ИдентификаторКластера + """ ";
Предлагаю код вида
`КомандаВыполнения = КомандаВыполнения + "--cluster=""" + ИдентификаторКластера + """ ";`

выделить в спец.метод `ДобавитьПараметр(КомандаВыполнения , "--cluster=", "ИдентификаторКластера ");`

тогда код будет намного легче читать и не будет дублирования кучи кавычек.

2021-06-01 10:16 UTC, artbear commented on src/Классы/КомандаСоздатьИнформационнуюБазу.os
> +	Функция ИдентификаторКластера()
в этом методе лишние отступы вправо ( 

по сравнению с остальным кодом.

2021-06-01 10:16 UTC, artbear commented on src/Классы/КомандаСоздатьИнформационнуюБазу.os
> +		КомандаВыполнения = КомандаВыполнения + "--cluster=""" + ИдентификаторКластера + """ ";
а реализовать через 
`КомандаВыполнения  = КомандаВыполнения  + СтрШаблон(" %1=""%2"" ", Ключ, Значение);`

2021-06-01 10:16 UTC, artbear commented on src/Классы/КомандаУдалитьИнформационнуюБазу.os
> +Функция РазобратьПоток(Знач Поток) Экспорт
1 метод РазобратьПоток дублируется в 2х классах
2 почему он экспортный в обоих, хотя не вызывается извне

предлагаю перенести его и подченные методы (один или два) в класс ОбщиеМетоды

2021-06-01 10:16 UTC, artbear commented on src/Классы/КомандаУдалитьИнформационнуюБазу.os
> +Функция КлючиАвторизацииВБазе()
очень много методов дублируются в обоих новых классах.

предлагаю для исключения дублирования сделать или новый модуль или новый класс, куда перенести эту функциональность.

2021-06-01 10:16 UTC, artbear commented on src/Классы/КомандаУдалитьИнформационнуюБазу.os
> +Перем мИдентификаторБазы;
аналогично переименовать имена переменных согласно стандарту 1С

2021-08-21 07:01 UTC, artbear commented
@Barrya42 будешь исправлять мои замечания?

2021-09-28 10:06 UTC, Barrya42 commented
Да, но позже.

сб, 21 авг. 2021 г. в 14:01, Artur Ayukhanov ***@***.***>:

> @Barrya42 <https://github.com/Barrya42> будешь исправлять мои замечания?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/vanessa-opensource/vanessa-runner/pull/437#issuecomment-903071707>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABWAQ544ZAGPCD63OV2DJ23T55FLZANCNFSM45TIPGTQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2022-03-27 08:26 UTC, artbear commented
@Barrya42 не дождался твоих исправлений, начал сам делать. см. https://github.com/vanessa-opensource/vanessa-runner/pull/500

2022-03-27 08:27 UTC, artbear commented on src/Классы/КомандаСоздатьИнформационнуюБазу.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--db-pwd", "Пароль пользователя БД");
исправил в своем ПР

2022-03-27 08:27 UTC, artbear commented on src/Классы/КомандаСоздатьИнформационнуюБазу.os
> +
исправил в своем ПР

2022-03-27 08:27 UTC, artbear commented on src/Классы/КомандаСоздатьИнформационнуюБазу.os
> +Перем мНастройки;
исправил в своем ПР

2022-03-27 08:27 UTC, artbear commented on src/Классы/КомандаСоздатьИнформационнуюБазу.os
> +	Функция ИдентификаторКластера()
исправил в своем ПР

2022-03-27 08:37 UTC, artbear commented on src/Классы/КомандаУдалитьИнформационнуюБазу.os
> +Перем мИдентификаторБазы;
Исправил в своем ПР

2022-03-27 13:31 UTC, artbear commented on src/Классы/КомандаУдалитьИнформационнуюБазу.os
> +Функция РазобратьПоток(Знач Поток) Экспорт
исправил в своем ПР

2022-03-27 13:31 UTC, artbear commented on src/Классы/КомандаУдалитьИнформационнуюБазу.os
> +Функция КлючиАвторизацииВБазе()
исправил в своем ПР

2022-03-27 13:35 UTC, artbear commented
Закрываю этот ПР, т.к. реализация сделана в соседнем ПР.

@Barrya42 большое спасибо!

2022-03-27 13:35 UTC, closed without merging