Добавлен пример файла деплоймента
vanessa-opensource/vanessa-runner pull request #447
Opened 2021-09-10 12:32 UTC by maximsamokhval

По #446 
Добавлен пример файла деплоймента с использованием rac/ras, запуском клиентского приложения с ключем ЗапуститьОбновлениеИнформационнойБазы

2021-09-14 13:50 UTC, artbear reviewed
@maximsamokhval отпишись, будет исправлять батник по моему комментарию?

если да, я подожду исправления и потом смержу.
если нет, смержу сразу

но даже если не будешь исправлять, лучше бы комментарий про последовательное выполнение добавить.

2021-09-14 13:50 UTC, artbear commented on examples/deploy.cmd
> +@call vrunner session unlock --ras %RASSERVER%:%RASPORT% --rac %RACPATH% --db %DBNAME% --db-user %DBUSER% --db-pwd %DBPWD% --uccode %UCCODE%
Хороший батник.

только у батников одна проблема (
- простое написание команд друг за другом не позволяет прерывать выполнение следующих команд, если очередная команда выдает ошибку

поэтому лучше
- или добавлять проверку на ERRORLEVEL
- или использовать скрипт на 1скрипт с объектом Команда
  - init.os, например

2021-09-14 13:52 UTC, maximsamokhval commented
@artbear Я попробую исправить , если не получится , могу к тебе обратиться за примером ?

2021-09-15 14:10 UTC, maximsamokhval commented
@artbear переделал на 1скрипт, получилось 2 файла : батник, в котором устанавливаются переменные окружения и скрипт исполнения

2021-09-16 11:46 UTC, maximsamokhval commented
@artbear убрал пока батник, оставил 1script

2021-09-18 14:05 UTC, artbear requested changes
небольшие правки и можно будет смержить.

2021-09-18 14:05 UTC, artbear commented on examples/deploy.os
> +	RACPATH = "C:\Program Files\1cv8\%V8VERSION%\bin\rac.exe";
что за переменные среды V8VERSION ?

ее нет в скрипте. как она устанавливается?

2021-09-18 14:05 UTC, artbear commented on examples/deploy.os
> +	// Завершаем сеанс только Кофигуратора, чтобы выполнить обновление --filter appid=Designer
опечатка Кофигуратора

2021-09-18 14:05 UTC, artbear commented on examples/deploy.os
> +	Возврат Команда.ПолучитьВывод();
метод ИсполнитьКоманду лучше сделать процедурой. т.к. его результат в виде лога не важен.
1 лог команды сразу показывается, при выполнении команды
2 если возникнет ошибка, то Команды.Исполнить() выбросит исключение и до Возврата дело все равно не дойдет.

2021-09-18 14:05 UTC, artbear commented on examples/deploy.os
> +	Возврат Истина;
и метод ВыполнитьОбновление также лучше сделать процедурой

2021-09-18 14:05 UTC, artbear commented on examples/deploy.os
> +Перем LOCKSTARTAT;
переменная непонятна. это время ожидания, верно?
тогда название переменной не отвечает ее назначению. лучше переназвать.

2021-09-19 16:48 UTC, maximsamokhval commented on examples/deploy.os
> +Перем LOCKSTARTAT;
![image](https://user-images.githubusercontent.com/24194977/133935804-e4f3b5e4-747d-4656-9156-e82a49d14ee6.png)
имя переменной LOCKSTARTAT взято из справки по vrunner

2021-09-19 16:53 UTC, maximsamokhval commented on examples/deploy.os
> +	RACPATH = "C:\Program Files\1cv8\%V8VERSION%\bin\rac.exe";
@artbear V8VERSION  заменил на RUNNER_v8version, переменные старался именовать как в vrunner

2021-09-19 16:59 UTC, maximsamokhval commented on examples/deploy.os
> +	Возврат Команда.ПолучитьВывод();
Исправлено, согласно замечаниям

2021-09-19 16:59 UTC, maximsamokhval commented on examples/deploy.os
> +	Возврат Истина;
Исправлено, согласно замечаниям

2021-09-20 05:48 UTC, maximsamokhval commented
@artbear переменные переименованы на русский язык, функции заменены на процедуры

2021-09-27 13:13 UTC, artbear commented on examples/deploy.os
> +	Вер)сия1С = "8.3.18.1334";
Опечатка Вер)сия1С

2021-09-27 13:17 UTC, artbear requested changes
перед финишным рывком неожиданно вкрались ошибки )

2021-09-27 13:17 UTC, artbear commented on examples/deploy.os
> +	RACPATH = "C:\Program Files\1cv8\""RUNNER_v8version""\bin\rac.exe";
"C:\Program Files\1cv8\""RUNNER_v8version""\bin\rac.exe" - неверно

в этом случае финальный путь будет выглядеть примерно так `C:\Program Files\1cv8\"8.3.10.2772"\bin\rac.exe`
т.е. внутри будут лишние кавычки (

2021-09-27 13:17 UTC, artbear commented on examples/deploy.os
> +	RACPATH = СтрЗаменить(RACPATH, "V8VERSION", Версия1С);
пытаемся менять "V8VERSION", а в строке выше написано в другом регистре  RUNNER_v8version (

2021-09-27 13:17 UTC, artbear commented on examples/deploy.os
> +	СообщениеБлокировки = "Уважаемые пользователи. В данный момент проводится плановое обновление базы данных.";
предлагаю без точки, а обращением
"Уважаемые пользователи, в данный момент проводится плановое обновление базы данных."

2021-10-04 12:21 UTC, maximsamokhval commented on examples/deploy.os
> +	RACPATH = "C:\Program Files\1cv8\""RUNNER_v8version""\bin\rac.exe";
@artbear убрал

2021-10-04 13:04 UTC, merged

2021-10-04 13:05 UTC, artbear commented
@maximsamokhval Большое спасибо!