Команда vrunner create
vanessa-opensource/vanessa-runner pull request #449
Opened 2021-09-14 12:35 UTC by leobrn

реализация #448 

сделанные изменения:
- Добавлен файл КомандаСоздатьПроект.os 
- Скорректирован файл ПараметрыСистемы.os  для работы с новой командой

2021-09-14 13:13 UTC, artbear requested changes
Есть предложения по улучшению, чтобы в будущем команду не пришлось постоянно доделывать.

2021-09-14 13:13 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +КонецФункции
сделай перевод строки, важно для Гит-истории

2021-09-14 13:13 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Сообщить(Команда.ПолучитьВывод());
и здесь простое Сообщить неудобно, удобнее пользоваться logos

2021-09-14 13:13 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +		Сообщить("Не удалось клонировать шаблон:");
и здесь лучше Лог.Ошибка вместо Сообщить

2021-09-14 13:13 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	КодВозврата = Команда.Исполнить();
код этого метода очень похож на метод ВыполнитьКомандуПоСтрокеЗапуска

лучше отрефакторить.

2021-09-14 13:13 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Библиотеки.Добавить("precommit1c");
Загрузить этот файл в структуру совсем несложно.

есть глобальные методы для этого

2021-09-14 13:44 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +			ВыполнитьКомандуПоСтрокеЗапуска("gitrules install");
а еще важно, чтобы неудача в 1й команде не давала выполнить вторую и далее команды.

а сейчас это возможно

2021-09-16 07:42 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +#Использовать gui
в packagedef нужно добавить зависимость от библиотеки gui

2021-09-16 07:51 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Лог.Информация("Начат процесс создания проекта");
Давай упростим сообщение - "Создаю проект..."

2021-09-16 07:54 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Лог.Информация("Шаблон для установки: %1", Шаблон);
Предлагаю - Использую шаблон проекта %1

2021-09-16 07:56 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +		КонецЦикла;
вместо цикла лучше юзать готовый метод `Команда.ДобавитьПараметры(Параметры)`

2021-09-16 07:57 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Результат = КодВозврата = 0;
плохое название Результат для булевого значения.

предлагаю заменить на Успешно

2021-09-16 08:00 UTC, artbear commented on examples/example.env.json
>  }
и тут сделай перевод строки

2021-09-16 08:07 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Возврат Результат;
лишняя переменная Результат, сразу делай `Возврат ВыполнитьКомандуПоСтрокеЗапуска("git", ПараметрыКоманды);`

2021-09-16 08:07 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +		Если НЕ Результат Тогда
и тут Результат - плохое имя переменной.

лучше УспешноКлонирован

2021-09-16 08:09 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Возврат "init-project";
имя дублируется с ВозможныеКоманды().СоздатьПроект

предлагаю использовать вызов ВозможныеКоманды().СоздатьПроект

2021-09-16 08:10 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +КонецФункции
в этом методе вроде перемудрил.
ты же раньше, при инициализации уже получил Пакеты в Настройки.Пакеты, верно?

зачем здесь еще раз читать файл настроек??

2021-09-16 08:12 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +КонецФункции
он читает настройки клонированного шаблона

2021-09-16 08:15 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +КонецФункции
надо проверку добавить, что когда настройки не через --settings тогда смотрим пакеты из шаблона

2021-09-16 08:24 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +		Пакеты = ПакетыШаблона();
этот код выполняется при условии Настройки.ИспользоватьШаблон, что странно
т.к. в джейсон-файле Шаблон и Пакеты находятся в разных блоках
и вообще не очень зависимы друг от друга.

предлагаю или вынести этот код
или как я ранее написал, метод подозрительный и вообще может быть удален.

2021-09-16 08:27 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Возврат СтруктураПакета;
зачем нужен этот метод?
фактически он возвращает те же данные, что уже есть в Пакет

предлагаю просто использовать Пакет.ХХХ, а этот метод удалить

2021-09-16 08:29 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +Функция ПакетДляДобавления(Имя, Команды, Использовать = Ложь)
Почему в этом методе значение по умолчанию такое? Использовать = Ложь

ведь в этом случае, если не задать файл настроек, ни один пакет не будет установлен.
т.е. клонируется шаблон, а пакеты не поставятся.

предлагаю исправить на Истина

2021-09-16 08:36 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +Функция ПакетДляДобавления(Имя, Команды, Использовать = Ложь)
Это для формы, когда у нас нету пакетов в настройках или мы не указываем файл настроек мы предлагаем пользователю три пакета, которые зашиты. По умолчанию они выключены.

2021-09-16 08:40 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +		Отказ = ВыполнитьКомандуПоСтрокеЗапуска(СтрокаКоманды);
подозрительный код с Отказом.
1 Почему `Отказ = ВыполнитьКомандуПоСтрокеЗапуска(СтрокаКоманды);` ?
метод возвращает Истину, если выполнен не успешно?
очень похоже на ошибку

2 а вообще лучше сразу в цикле, без переменной Отказ
Если Не ВыполнитьКомандуПоСтрокеЗапуска(СтрокаКоманды) Тогда
  Прервать;
КонецЕсли

2021-09-16 08:45 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	НастройкиИзФайла = ОбщиеМетоды.ПрочитатьФайлJSON(ПутьКФайлуНастроек);
Нужно решить, что делать, если в шаблоне не будет базового файла ./env.json

выдаем ошибку?
или ничего не делаем?

и реализовать соответствующий код

2021-09-16 08:46 UTC, artbear requested changes
Есть дополнения и замечания.

2021-09-16 08:47 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +Функция ПакетДляДобавления(Имя, Команды, Использовать = Ложь)
да, я понял, но мне казалось, что для пользователя удобнее, когда по умолчанию пакеты включены.
Лады, решай сам, оставить Ложь или исправить на Истина

2021-09-16 08:48 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Возврат СтруктураПакета;
Или здесь проблема в том, что Пакет - это соответствие, и нельзя юзать Пакет.ХХХ, а нужно Пакет.Получить("ХХХ") или Пакет["XXX"] ?

2021-09-16 08:52 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +	Возврат СтруктураПакета;
> Или здесь проблема в том, что Пакет - это соответствие, и нельзя юзать Пакет.ХХХ, а нужно Пакет.Получить("ХХХ") или Пакет["XXX"] ?

да

2021-09-16 08:54 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +Функция ПакетДляДобавления(Имя, Команды, Использовать = Ложь)
> да, я понял, но мне казалось, что для пользователя удобнее, когда по умолчанию пакеты включены.
> Лады, решай сам, оставить Ложь или исправить на Истина

оставлю гитсинк включенным по умолчанию, как наиболее часто используемый

2021-09-16 08:57 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +	НастройкиИзФайла = ОбщиеМетоды.ПрочитатьФайлJSON(ПутьКФайлуНастроек);
сейчас будет открыта форма с пакетами по умолчанию т.к не смогли определить пакеты в шаблоне. Можно вывести сообщение, что не найден файл с настройками и будет открыта форма

2021-09-16 08:59 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +		Отказ = ВыполнитьКомандуПоСтрокеЗапуска(СтрокаКоманды);
Вообще использование стиля работы через Отказ для меня всегда подозрительно, слишком легко напортачить.
что в 1С, что в 1скрипт.

2021-09-16 09:01 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	НастройкиИзФайла = ОбщиеМетоды.ПрочитатьФайлJSON(ПутьКФайлуНастроек);
ИМХО сейчас будет исключение, т.к. не будет найден файл (

предлагаю добавить проверку существования файла
если его нет, выдавать сообщение-предупреждение `"В шаблоне проекта не найден файл с  базовыми настройками ./" + ОбщиеМетоды.ИмяФайлаНастроек()`
ну и показывать формы с пакетами по умолчанию.

2021-09-16 09:02 UTC, artbear commented on examples/example.env.json
>  }
перевод строки нужно делать на последней строке, а не на предпоследней

2021-09-16 09:04 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Возврат СтруктураПакета;
тогда лады, закрываю замечание

2021-09-16 09:15 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +	НастройкиИзФайла = ОбщиеМетоды.ПрочитатьФайлJSON(ПутьКФайлуНастроек);
Функция ОбщиеМетоды.ПрочитатьФайлJSON вернет же пустое соответствие 
`ФайлСуществующий = Новый Файл(ИмяФайла);
	Если Не ФайлСуществующий.Существует() Тогда
		Возврат Новый Соответствие;
	КонецЕсли;`

2021-09-16 09:26 UTC, leobrn commented on examples/example.env.json
>  }
Добавил

2021-09-16 09:26 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +КонецФункции
Доработал

2021-09-16 09:26 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +		Пакеты = ПакетыШаблона();
Обсудили это в telegram

2021-09-16 09:27 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +		Отказ = ВыполнитьКомандуПоСтрокеЗапуска(СтрокаКоманды);
Исправил

2021-09-16 09:34 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	КонецЕсли;
Давай упростим код и напишем так
```bsl
	Команда.УстановитьСтрокуЗапуска(СтрокаЗапуска);
	Если ЗначениеЗаполнено(Параметры) Тогда
		Команда.ДобавитьПараметры(Параметры);
	КонецЕсли;
```

2021-09-16 09:36 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	КонецЕсли;
т.к. вывод команды всегда показывается, тогда лучше сразу его и выдавать через класс Команда

т.е. написать Команда.ПоказыватьВыводНемедленно(Истина);
и сразу возвращать `Возврат КодВозврата = 0;` без доп.показа вывода команды

2021-09-16 09:38 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +		Если НЕ Значение Тогда
имя переменной Значение не подходит.
лучше ИспользоватьПакет

2021-09-16 09:39 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +	КонецЕсли;
Но тут в консоли видно строки где Информация или Ошибка. А в данном случае как будет?

2021-09-16 09:40 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Пакеты = Неопределено;
лучше всегда возвращать элементы одного типа.

если обычно возвращаем коллекцию, то вместо Неопределено лучше вернуть пустую коллегкцию.

предлагаю Пакеты = Новый Массив;

2021-09-16 09:40 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	Пакеты = Неопределено;
ну и имя переменной поменять - вместо Пакеты назвать Результат

2021-09-16 09:43 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	КонецЕсли;
Да. разделения не будет.

давай тогда в случае ошибки выводить
Лог.Ошибка("Пакет %1. Команда не выполнена", Пакет.Имя);

в этом случае все будет видно и будет спец.строка для поиска ошибок

2021-09-16 09:44 UTC, artbear commented
@leobrn еще просьба - приложи скриншот формы установки в шапку ПР
можно тот же, что ты в телеграм постил.

2021-09-16 10:11 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +	Пакеты = Неопределено;
надо тогда добавить проверку на неопределённо  НастройкиПроекта.Получить("Пакеты")

2021-09-16 10:15 UTC, leobrn commented on src/Классы/КомандаСоздатьПроект.os
> +	КонецЕсли;
да только сейчас это общая функция, для всех исполняемых команд, не только для пакетов.  надо тогда выводить лог по ошибке Лог.Ошибка("Пакет %1. Команда не выполнена", Пакет.Имя); в функции ВыполнитьКомандыУстановкиПакета и передавать не команды, а сам пакет

2021-09-16 12:21 UTC, artbear commented on src/Классы/КомандаСоздатьПроект.os
> +	КонецЕсли;
этот участок не трогай, оставляем как есть

2021-09-16 12:52 UTC, artbear approved these changes
Все исправили.
УРА!

2021-09-16 12:53 UTC, merged

2021-09-16 12:54 UTC, artbear commented
@leobrn Спасибо за новую замечательную команду и ее реализацию.

Поздравляю с присоединением в команду контрибьюторов!
В нашем полку прибыло.