Исправления по #458
vanessa-opensource/vanessa-runner pull request #459
Opened 2021-09-30 18:17 UTC by SidnevAV

Перенёс вызов ОбеспечитьПустойКаталог

2021-09-30 18:18 UTC, SidnevAV commented
#458

2021-10-02 15:43 UTC, artbear requested changes
нужно убрать пару лишних добавленных строк

2021-10-02 15:43 UTC, artbear commented on src/Классы/КомандаПроверкаПроектаEDT.os
> +		ФС.ОбеспечитьПустойКаталог(ПутьОтчетаВФорматеAllure);
зачем очищать каталог без имени? )

2021-10-02 15:43 UTC, artbear commented on src/Классы/КомандаПроверкаПроектаEDT.os
> +		ФС.ОбеспечитьПустойКаталог(ПутьОтчетаВФорматеAllure2);
и здесь каталог без имени

2021-10-02 18:04 UTC, SidnevAV commented on src/Классы/КомандаПроверкаПроектаEDT.os
> +		ФС.ОбеспечитьПустойКаталог(ПутьОтчетаВФорматеAllure);
Тяжелая неделя на работе, забыл "иначе" добавить.

2021-10-02 18:04 UTC, SidnevAV commented on src/Классы/КомандаПроверкаПроектаEDT.os
> +		ФС.ОбеспечитьПустойКаталог(ПутьОтчетаВФорматеAllure2);
поправил

2021-10-02 18:06 UTC, SidnevAV commented on src/Классы/КомандаПроверкаПроектаEDT.os
> +		ФС.ОбеспечитьПустойКаталог(ПутьОтчетаВФорматеAllure);
Раньше в проверке проекта EDT была очистка в модуле "ГенерацияОтчетов", перенес сюда по аналогии с синтаксис проверкой.

2021-10-04 13:25 UTC, merged