Возможность указать переменные среды в Json
vanessa-opensource/vanessa-runner pull request #511
Opened 2022-04-20 12:04 UTC by Segate-ekb

При использовании Jenkins хочется формировать файл настроек json с использованием переменных среды:
Например:
```
{
    "$schema": "https://raw.githubusercontent.com/vanessa-opensource/vanessa-runner/develop/vanessa-runner-schema.json",
    "default": {
        "--ibconnection": "/S${Server}/${Base}",
        "--db-user": "${CREDENTIALS_1C_USR}",
        "--db-pwd": "${CREDENTIALS_1C_PSW}",
        "--v8version": "8.3.15.1656",
        "--uccode": "${UCCODE}"
    }
}
```

данный пр реализует такую возможность, позволяя единообразно хранить настройки, и при этом не хранить конфиденциальную информацию внутри JSON

2022-04-20 12:48 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +				Если Элемент.Значение = "1" ИЛИ Нрег(ЗначениеПодстановки) = "истина" ИЛИ Нрег(ЗначениеПодстановки) = "true" Тогда
пропущено Если Элемент.Значение = "1" - нет замены на ЗначениеПодстановки

2022-04-20 12:53 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +		РВЗамены = Новый РегулярноеВыражение("\${" + Совпадение.значение + "}");
такой шаблон регулярки лучше не юзать, т.к. в пользовательском значении могут быть спец.символы регулярки - точки, слеши и т.п.

почему бы просто через СтрЗаменить не поменять?

2022-04-20 12:54 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +		Лог.Отладка("Значение переменной среды """ + Совпадение.значение + """изменено на """ + ЗначениеПеременнойСреды + """");
Лог.Отладка и Лог.ХХХ позволяют юзать шаблоны %1 аналогично СтрШаблон.

и подобные строки с конкатенацией лучше заменить на `Лог.Отладка("текст с процентами", значение1, значение2...);`

2022-04-20 12:54 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +		Лог.Отладка("Значение параметра:" + ЗначениеПодстановки + " Тип:" + ТипЗнч(ЗначениеПодстановки));
и здесь лучше юзать шаблонную строку в Лог.Отладка

2022-04-20 12:56 UTC, artbear requested changes
есть замечания

2022-04-20 13:10 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +		Лог.Отладка("Значение переменной среды """ + Совпадение.значение + """изменено на """ + ЗначениеПеременнойСреды + """");
fix

2022-04-20 13:10 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +		РВЗамены = Новый РегулярноеВыражение("\${" + Совпадение.значение + "}");
Согласен, переделал

2022-04-20 13:11 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +		Лог.Отладка("Значение параметра:" + ЗначениеПодстановки + " Тип:" + ТипЗнч(ЗначениеПодстановки));
fix

2022-04-20 14:07 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +			КонецЕсли;
при таком коде нельзя передать пустое значение переменной среды.

предлагаю явно заменять шаблон с именем на пустоту

2023-01-26 17:36 UTC, merged

2023-01-26 17:37 UTC, artbear commented
@Segate-ekb Большое спасибо за ПР и за ожидание его принятия!

я слегка поправил регулярку и смержил. если не согласен с моей правкой, пиши

2023-01-26 17:37 UTC, artbear commented
Отличный и нужный ПР!