Сравнение конфигураций
vanessa-opensource/vanessa-runner pull request #523
Opened 2022-08-25 13:58 UTC by Borisskin

Добавил команду поддержки функционала v8runner - отчет сравнения конфигураций.
Параметры команды содержат расширение функционала из пулл-реквеста - [сравнение двух файлов конфигураций](https://github.com/oscript-library/v8runner/pull/145).

2023-01-26 17:15 UTC, artbear commented
@Borisskin Указанный связанный ПР смержен, но релиз v8runner пока, на 26.01.2023, не выпущен.

К текущему ПР нужно вернуться после выпуска релиза v8runner 

Изменяю заголовок ПР и оставляю его в ожидании

2023-01-26 17:24 UTC, artbear requested changes
есть замечания

2023-01-26 17:24 UTC, artbear commented on src/Классы/КомандаСравнитьКонфигурации.os
> +		"Путь к файлу cf/cfe, с которым идёт сравнение конфигурации");
Нужно указать, что параметр является обязательным в этой строке. пользователю так будет понятно.

2023-01-26 17:24 UTC, artbear commented on src/Классы/КомандаСравнитьКонфигурации.os
> +		"Путь к файлу, где должен быть сохранён отчет");
1 Нужно указать, что параметр является обязательным в этой строке. пользователю так будет понятно.

2 лучше передвинуть этот обязательный параметр в начало списка, чтобы обязательные параметры были в самом начале списка.

предлагаю такой порядок
- 1й файл
- далее 2 обязательных параметра
- затем все остальные

2023-01-26 17:24 UTC, artbear commented on src/Классы/КомандаСравнитьКонфигурации.os
> +		Если ЗначениеЗаполнено(ТипОтчета) И ТипОтчета <> "Full" Тогда
нужно сравнить через НРег для исключения регистрозависимости

2023-01-26 17:24 UTC, artbear commented on src/Классы/КомандаСравнитьКонфигурации.os
> +		Если ЗначениеЗаполнено(ФорматОтчета) И ФорматОтчета <> "txt" Тогда
и тут нужно сравнить через НРег для исключения регистрозависимости

2023-02-01 08:30 UTC, Borisskin commented on src/Классы/КомандаСравнитьКонфигурации.os
> +		Если ЗначениеЗаполнено(ФорматОтчета) И ФорматОтчета <> "txt" Тогда
Привет. Смогу исправить, как разберусь со здоровьем. Пока свободного времени просто засесть за комп - нет.

2023-03-04 10:40 UTC, Borisskin commented
Исправил замечания. Указал обязательные параметры. Порядок аналогичен тому, что сейчас в pr к v8runner.
В самом v8runner[ добавил новый pr](https://github.com/oscript-library/v8runner/pull/151), т.к. в прошлый раз ошибочно в ветку develop отправлял, потому в релиз оно и не попадало.

2023-03-11 13:39 UTC, artbear commented
https://github.com/oscript-library/v8runner/pull/151 смержен, но релиз не выпущен.

Опять ждем.

2024-03-05 12:20 UTC, Borisskin commented
> [oscript-library/v8runner#151](https://github.com/oscript-library/v8runner/pull/151) смержен, но релиз не выпущен.
> 
> Опять ждем.

В релизе [1.9.1](https://hub.oscript.io/download/v8runner/v8runner-1.9.1.ospx) c 28.02.2024
В [мастер-ветке](https://github.com/oscript-library/v8runner), но релизов в гитхабе не выпускают.

2024-06-29 06:53 UTC, artbear commented
Релиз v8runner подготовлен к выпуску, мелкие организационные детали и все

далее я вмержу текущий ПР в ванесса-раннер, чтобы он попал в свежий релиз ванесса-раннер

2024-06-29 07:37 UTC, merged

2024-06-29 07:37 UTC, artbear commented
@Borisskin Большое спасибо! я выпустил релиз v8runner, и смержил этот ПР, чтобы он попал в релиз!