Указание версии конфигурации в имени сохраняемого файла
vanessa-opensource/vanessa-runner pull request #559
Opened 2023-04-22 05:41 UTC by yukon39

2023-04-26 17:30 UTC, artbear requested changes
небольшое замечание, как и в соседнем ПР https://github.com/vanessa-opensource/vanessa-runner/pull/563

2023-04-26 17:30 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +Функция ВерсияФайлаКонфигурации(Знач ПутьПроектаКонфигурации)
и здесь дубль уже существующего метода ВерсияКонфигурации

2023-04-27 07:07 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +Функция ВерсияФайлаКонфигурации(Знач ПутьПроектаКонфигурации)
как я уже писал в соседнем ПР - лучше сделать реализацию этого метода через вызов существующего метода, возвращающего коллекцию
и добавить вызов исключения, если результат пустой

2023-04-27 07:08 UTC, artbear requested changes
исправить копипаст кода

2023-04-27 11:30 UTC, yukon39 commented on src/Классы/МенеджерВерсийФайлов1С.os
> +Функция ВерсияФайлаКонфигурации(Знач ПутьПроектаКонфигурации)
убраны изменения

2023-04-27 14:41 UTC, merged