Добавлен режим формирования файлов поставки из исходников.
vanessa-opensource/vanessa-runner pull request #563
Opened 2023-04-25 23:56 UTC by yukon39

Реализует #562

2023-04-26 17:25 UTC, artbear requested changes
Есть замечания

2023-04-26 17:25 UTC, artbear commented on src/Классы/КомандаСоздатьФайлПоставки.os
> +	ЗагружатьВТекущую = ПараметрыКоманды["--current"];
не реализован вариант с "-с", указанный в описании параметра "--current"

2023-04-26 17:25 UTC, artbear commented on src/Классы/КомандаСоздатьФайлПоставки.os
> +	МенеджерВерсийФайлов1С = Новый МенеджерВерсийФайлов1С;
МенеджерВерсийФайлов1С здесь не используется, пересоздается в методе СоздатьФайлПоставки

2023-04-26 17:25 UTC, artbear commented on src/Классы/КомандаСоздатьФайлПоставки.os
>  		"Путь к результату - выгружаемому файлу поставки конфигурации (*.cf)");
нужно в описании кратко задокументировать использование "$version"

2023-04-26 17:25 UTC, artbear commented on src/Классы/КомандаСоздатьФайлПоставки.os
> +	Парсер.ДобавитьПараметрФлагКоманды(ОписаниеКоманды, "--current", "Флаг загрузки в указанную базу или -с");
предлагаю дополнить "Флаг загрузки исходников в указанную ИБ. Краткий вариант -с")

2023-04-26 17:25 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +Функция ВерсияФайлаКонфигурации(Знач ПутьПроектаКонфигурации)
ты заново реализовал уже существующий метод ВерсияКонфигурации )
- одно отличие - текущий метод не выдает исключение

Предлагаю использовать существующий метод вместо нового метода

2023-04-26 18:54 UTC, yukon39 commented on src/Классы/КомандаСоздатьФайлПоставки.os
> +	ЗагружатьВТекущую = ПараметрыКоманды["--current"];
Добавлен короткий вариант команды

2023-04-26 18:55 UTC, yukon39 commented on src/Классы/КомандаСоздатьФайлПоставки.os
> +	МенеджерВерсийФайлов1С = Новый МенеджерВерсийФайлов1С;
Исправлено - Менеджер версий теперь создается один раз при выполнении команды

2023-04-26 18:55 UTC, yukon39 commented on src/Классы/КомандаСоздатьФайлПоставки.os
>  		"Путь к результату - выгружаемому файлу поставки конфигурации (*.cf)");
Расширено описание параметра

2023-04-26 19:06 UTC, yukon39 commented on src/Классы/МенеджерВерсийФайлов1С.os
> +Функция ВерсияФайлаКонфигурации(Знач ПутьПроектаКонфигурации)
Это отдельный "единичный" метод. Метод `ВерсияКонфигурации ` возвращает соответствие из всех найденных конфигураций внутри каталога.

Данные метод предназначен для возврата только одной версии. Метод переиспользует уже существующую логику приватных методов.

2023-04-27 07:05 UTC, artbear requested changes

2023-04-27 07:05 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +Функция ВерсияФайлаКонфигурации(Знач ПутьПроектаКонфигурации)
все-таки лучше этот метод реализовать через вызов уже существующего метода для исключения копипаста

добавить только проверку того, что результат не пустой, тогда выдать исключение из текущего метода

2023-04-27 10:37 UTC, yukon39 commented on src/Классы/МенеджерВерсийФайлов1С.os
> +Функция ВерсияФайлаКонфигурации(Знач ПутьПроектаКонфигурации)
Исправлено. Убран дополнительный приветный метод

2023-04-27 10:48 UTC, artbear approved these changes

2023-04-27 10:48 UTC, merged