Issue-564
vanessa-opensource/vanessa-runner pull request #565
Opened 2023-04-26 00:13 UTC by yukon39

Реализует #564

2023-04-26 17:11 UTC, artbear requested changes
есть замечания

2023-04-26 17:11 UTC, artbear commented on src/Классы/КомандаИнициализацияОкружения.os
> +		МенеджерКонфигуратора.ОбновитьКонфигурациюБазыДанных(Ложь);
блок кода, где используется МенеджерКонфигуратора, нужно помещать в Попытку-Исключение с передачей исключения дале

пример такого блока есть выше по коду

2023-04-26 17:11 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +// Поиск файла полходящего под шаблон номера версии.
опечатка "полходящего"

2023-04-26 17:11 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +		Если РегулярноеВыражение.Совпадает(НайденныйФайл.Имя) Тогда
такой код найдет любой подходящий файл, без учета расширения.

т.е. может найтись не файл конфигурации.

предлагаю доработать для поиска конфигураций\расширений\обработок\отчетов, остальные файлы игнорировать.

2023-04-26 17:14 UTC, artbear commented on src/Классы/КомандаИнициализацияОкружения.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--cf", "Путь к cf-файлу конфигурации");
и нужно добавить краткую доку в ком.строке на использование "$version"

2023-04-26 19:23 UTC, yukon39 commented on src/Классы/МенеджерВерсийФайлов1С.os
> +		Если РегулярноеВыражение.Совпадает(НайденныйФайл.Имя) Тогда
Расширение файла учитывается. При формирвоании шаблона использыется имя файла, т.е. для поиска файла-шаблона "1cv8_$version.cf" будет использоваться регулярное выражение "1cv8_(\d+.\d+.\d+.\d+|\d+.\d+.\d+).cf"

2023-04-26 19:30 UTC, yukon39 commented on src/Классы/КомандаИнициализацияОкружения.os
> +		МенеджерКонфигуратора.ОбновитьКонфигурациюБазыДанных(Ложь);
Запуск вынесен в отдельный метод, в котором использована Попытка/Исключение

2023-04-26 19:32 UTC, yukon39 commented on src/Классы/МенеджерВерсийФайлов1С.os
> +		Если РегулярноеВыражение.Совпадает(НайденныйФайл.Имя) Тогда
Для оптимизации тут можно получить отбор по уже известному расширению из файла.

2023-04-26 19:49 UTC, yukon39 commented on src/Классы/МенеджерВерсийФайлов1С.os
> +		Если РегулярноеВыражение.Совпадает(НайденныйФайл.Имя) Тогда
Оптимизирован поиск с учетом расширения файла.
Добавлен отладочный вывод.

2023-04-26 19:49 UTC, yukon39 commented on src/Классы/КомандаИнициализацияОкружения.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--cf", "Путь к cf-файлу конфигурации");
Добавлено

2023-04-27 06:49 UTC, artbear commented on src/Классы/КомандаИнициализацияОкружения.os
> +	КонецПопытки;
забыт МенеджерКонфигуратора.Деструктор(); уже ПОСЛЕ Попытки

2023-04-27 06:51 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +		Если РегулярноеВыражение.Совпадает(НайденныйФайл.Имя) Тогда
Регулярка неточная получается - "1cv8_(\d+.\d+.\d+.\d+|\d+.\d+.\d+).cf"

".cf" означает, что ищется ЛЮБОЙ символ перед cf, а не это не обязательно точка

так что лучше или экранировать спец.символы, как, например, сделано в Ванесса-АДД, плагин РегулярныеВыражения

2023-04-27 06:52 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +		МаскаПоиска = "*" + Файл.Расширение;
а Файл.Расширение возвращает расширение с точкой или нет? ".cf" или "cf" ?
- проверь, плиз

если без точки, тогда код `МаскаПоиска = "*" + Файл.Расширение;` неверен.

2023-04-27 07:00 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +		Если РегулярноеВыражение.Совпадает(НайденныйФайл.Имя) Тогда
Я посмотрел детальнее, регулярка вообще неверна.

ты неверно используешь точку в шаблоне регулярки
. в шаблоне означает любой символ, а не точку

если нужна точка, то нужно ставить "\."

вот правильная регулярка для версии - (\d+\.\d+\.\d+\.\d+|\d+\.\d+\.\d+)

а вот правильная для 1cv8_$version.cf - 1cv8_(\d+\.\d+\.\d+\.\d+|\d+\.\d+\.\d+)\.cf - обрати внимание на последний \.

2023-04-27 07:00 UTC, artbear commented on src/Классы/МенеджерВерсийФайлов1С.os
> +	ШаблонПоиска = СтрЗаменить(Файл.Имя, ШаблонВерсии, "(\d+.\d+.\d+.\d+|\d+.\d+.\d+)");
ошибка в регулярке. см. замечания ниже

2023-04-27 07:00 UTC, artbear requested changes
еще нужны исправления

2023-04-27 10:46 UTC, yukon39 commented on src/Классы/КомандаИнициализацияОкружения.os
> +	КонецПопытки;
Он в основном же методе есть. 
![image](https://user-images.githubusercontent.com/4100597/234840008-e190eb4a-b8c4-4b5d-b205-9ec48dc79d2c.png)

2023-04-27 10:47 UTC, yukon39 commented on src/Классы/МенеджерВерсийФайлов1С.os
> +		МаскаПоиска = "*" + Файл.Расширение;
с точкой.

2023-04-27 11:07 UTC, artbear approved these changes

2023-04-27 11:07 UTC, merged