Добавлены переменные окружения для учетных данных администратора кластера
vanessa-opensource/vanessa-runner pull request #572
Opened 2023-04-28 06:02 UTC by yukon39

Реализует #571

2023-04-28 14:55 UTC, artbear requested changes

2023-04-28 14:55 UTC, artbear commented on src/main.os
> +	СоответствиеПеременных.Вставить("RUNNER_CLUSTER_USER", "--cluster-admin");
Название "RUNNER_CLUSTER_USER" не соответствует параметру "--cluster-admin"

будут неочевидные ошибки и вопросы

Предлагаю переназвать - RUNNER_CLUSTER_ADMIN

2023-04-28 14:59 UTC, yukon39 commented on src/main.os
> +	СоответствиеПеременных.Вставить("RUNNER_CLUSTER_USER", "--cluster-admin");
Тут смысл в том, что стандартный вызов `RUNNER_CLUSTER = credentials('CredentialsId') ` создаст именно такую пару переменных окружения.

Альтернативный вариант: 
`RUNNER_CLUSTERADMIN= credentials('CredentialsId') ` 
и соотвественно
RUNNER_CLUSTERADMIN_USER / RUNNER_CLUSTERADMIN_PWD

2023-05-10 07:54 UTC, yukon39 commented on src/main.os
> +	СоответствиеПеременных.Вставить("RUNNER_CLUSTER_USER", "--cluster-admin");
@artbear Проставляю тогда?
RUNNER_CLUSTERADMIN_USER / RUNNER_CLUSTERADMIN_PWD

2024-06-28 22:39 UTC, yukon39 commented
@artbear я разрулил конфликты слияния

2024-06-29 06:56 UTC, merged