[FEAT] Добавлен параметр --ibcmd для запуска команд с использованием утилиты ibcmd
vanessa-opensource/vanessa-runner pull request #601
Opened 2023-11-05 10:01 UTC by yukon39

Реализует #596 

Добавлен параметр --ibcmd для запуска команд с использованием утилиты ibcmd для команд:
* int-dev
* update-dev
* compileext
* decompileext
* loadext
* unloadext
* updateext
* compileexttocfe
* updatedb
* unload
* dump
* restore
* compile
* decompile
* load

2023-11-05 10:05 UTC, yukon39 commented
Для полноценной работы возможно понадобится новый релиз ibcmdrunner с уже принятыми PR. @alex-bob-lip

2023-11-07 06:56 UTC, alex-bob-lip commented
Круто! Постараюсь собрать релиз на этой неделе.

2023-11-08 07:50 UTC, alex-bob-lip commented
Новый релиз ibcmdrunner доступен для установки через opm

2023-11-08 15:45 UTC, yukon39 commented
Тогда ждем ревью от @artbear

2023-11-20 10:50 UTC, artbear requested changes

2023-11-20 10:50 UTC, artbear commented on tests/xunits/update-dev.os
> +//&Тест
по всему этому файлу отключены тесты (

зачем?

2023-11-22 06:39 UTC, artbear commented
@yukon39 у меня зависают тесты на `ТестДолжен_СобратьКонфигурациюИзИсходниковВТекущуюБазуIbcmd`

на такой команде ванесса-раннер
`ВходнойМассивПараметров <compile --ibconnection /F"E:\aayukhanov\temp\7\3jbkw2w3.nmc.tmp\db-data" --src C:\Users\aayukhanov\Documents\repo\vanessa-runner\tests\fixtures\cf --current --noupdate --ibcmd --root E:\aayukhanov\temp\7\3jbkw2w3.nmc.tmp --nocacheuse >`

низом виснет на 
`ОТЛАДКА - [oscript.lib.commands] - Полная строка запуска <cmd /c ""C:\Program Files\1Cv8\8.3.22.2175\bin\ibcmd.exe" infobase config support disable --db-path="E:\aayukhanov\temp\7\3jbkw2w3.nmc.tmp\db-data" --user=%IBCMD_IB_USR% --data="E:\aayukhanov\temp\7\4gif5pax.lr1.tmp"">`

Artur, [20.11.2023 14:26]
и еще тест завис `ТестДолжен_СобратьКонфигурациюИзИсходниковIbcmd`

Полная строка запуска 
`<cmd /c ""C:\Program Files\1Cv8\8.3.22.2175\bin\ibcmd.exe" infobase config import --db-path="E:\aayukhanov\temp\7\wqjvv04a.dic.tmp\db_data" --user=%IBCMD_IB_USR% --data="E:\aayukhanov\temp\7\wqjvv04a.dic.tmp" "C:\Users\aayukhanov\Documents\repo\vanessa-runner\tests\fixtures\cf"">`

Artur, [20.11.2023 14:35]
а вообще лучше зафиксировать версию, на которой гоняются эти тесты

иначе так и будем мучаться

тогда и стоит написать, что на 8.2.23.ХХХ проверена
на более ранних платформах могут возникать ошибки, которые уже исправлены в 8.3.23

2023-11-23 14:13 UTC, yukon39 commented
А где это написать?

Такой вопрос кстати: зачем там вызов снятия с поддержки? Конфигуратор и ibcmd нормально загружают конфигурацию даже если она на поддержке. 

Может вообще убрать этот дополнительный вызов?

2023-11-29 07:22 UTC, artbear commented
> А где это написать?
в документации на использование ibcmd

> 
> Такой вопрос кстати: зачем там вызов снятия с поддержки? Конфигуратор и ibcmd нормально загружают конфигурацию даже если она на поддержке.
> 
> Может вообще убрать этот дополнительный вызов?
была спец.доработка, по блейм посмотри, откуда взялся этот код и выйдешь на ишуз

2024-01-17 08:57 UTC, Segate-ekb commented
Мне кажется, что просто дописать что есть ограничение на 8.3.23 и все )

мол 8.3.22- используйте на свой страх и риск.
Можно для остраски выводить сообщение в лог, если версия платформы будет ниже 23

2024-01-28 17:47 UTC, Segate-ekb commented on packagedef
> +		.ЗависитОт("ibcmdrunner", "0.2.2")
Не забудь бампнуть версию до 0.2.3

2024-02-01 13:43 UTC, artbear commented on tests/xunits/update-dev.os
> +//&Тест
Исправлено.

2024-02-01 14:01 UTC, yukon39 commented on src/main.os
> -	ДополнитьЗначенияПараметров(Команда, ЗначенияПараметров);
Исправлено

2024-02-01 14:34 UTC, artbear requested changes

2024-02-01 14:34 UTC, artbear commented on tests/xunits/compile.os
> +Процедура ТестДолжен_СобратьКонфигурациюИзИсходниковВТекущуюБазуIbcmd() Экспорт
еще в этом модуле отключены тесты

2024-02-01 14:36 UTC, artbear commented on tests/xunits/compile.os
> +Процедура ТестДолжен_СобратьКонфигурациюИзИсходниковВТекущуюБазуIbcmd() Экспорт
уже исправлено.

2024-06-27 13:44 UTC, merged